### ISSUE TITLE
Problems with ip-reconciler

### ISSUE THREAD

**Issue by tardich** [k8snetworkplumbingwg/helm-charts#17]
Running this chart, I found out some issues:

1) Docker image: docker.io/dougbtv/whereabouts:latest (version 0.4) doesn't have support for ip-reconciler binary. In order to make it work, I had to user version 0.5.1, from there: docker.io/wjunott/whereabouts

2) clusterrole created is missing a rule for the above whereabouts version to work:
```
 - apiGroups:
  - whereabouts.cni.cncf.io
  resources:
  - overlappingrangeipreservations
  verbs:
  - list
  - get
  - create
  - delete
  - update
  - patch
  - watch
```
  with these changes, I was able to have whereabouts work, and the cronjob stopping from failing because of **file not found**
